name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change if necessary

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Change to match your project
      - name: Create .env file
        run: |
          echo "REACT_APP_SPOONACULAR_API_KEY=${{ secrets.REACT_APP_SPOONACULAR_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
  
      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: CI='' npm run build  # Adjust if your build command is different

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build  # Update this to match your build directory

      - name: Debug - List files after build
        run: ls -R
      

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
